name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: Modding-Restoration/build-geode-mod-2.1-fix-build@main
        with:
          build-config: RelWithDebInfo
          export-pdb: true
          sdk: 'v1.3.10'
          cli: 'v2.5.0'
          target: ${{ matrix.config.target }}